[build]
  command = "npm run build"
  publish = "build"
  functions = "functions"
[build.environment]
  NODE_VERSION = "14"
  # pnpm package.json prebuild compat
  NPM_FLAGS="--prefix=/"
[dev]
  command = "pnpm run dev"
  port = 8888
  targetPort = 3000
  publish = "build"
  framework = "#custom"